### ISSUE TITLE
Use `conda-verify`?

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/copier_template#41]
We have this warning in package builds:
```
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
```
Should we fix that?

**Comment by jl-wynen** [comment]
Sure, let's try it out!

**Comment by jl-wynen** [comment]
Tried it and it emits a single warning:
```
/tmp/tmpnf0srwsm/proj-23.11.0-py_0.tar.bz2: C1115 Found invalid license "BSD-3-Clause" in info/index.json
```
According to https://github.com/conda/conda-verify/blob/3b34286470dd1ceb495374e3ff7b52082084da8e/conda_verify/constants.py#L8 it only wants "BSD" as the license. But in practice we haven't encountered any problems with this. So I don't know if we should change it.

In any case, I tried changing it and the warning went away. I also added `license_file` in my test like this: (in meta.yaml)
```yaml
about:
  home: https://github.com/scipp/proj
  license: BSD
  license_file: LICENSE
  summary: testing
  description: testing
  dev_url: https://github.com/scipp/proj
  doc_url: https://scipp.github.io/proj
```
